#include <asn1/codegen/emit.hpp>

#include <algorithm>
#include <sstream>
#include <string_view>
#include <unordered_set>
#include <utility>

namespace asn1 {
namespace codegen {
namespace {

std::string cpp_ident(std::string_view name) {
  std::string out;
  out.reserve(name.size());
  for (char c : name) {
    if ((c >= 'a' && c <= 'z') || (c >= 'A' && c <= 'Z') || (c >= '0' && c <= '9') ||
        c == '_') {
      out.push_back(c);
    } else if (c == '-' || c == ' ') {
      out.push_back('_');
    }
  }
  if (out.empty() || (out[0] >= '0' && out[0] <= '9')) {
    out.insert(out.begin(), '_');
  }
  return out;
}

const ir::Type& resolve(const ir::Model& model, ir::TypeId id) {
  const ir::Type* t = &model.arena.get(id);
  while (t->kind == ir::TypeKind::Referenced && t->referenced.resolved != ir::kInvalidType) {
    t = &model.arena.get(t->referenced.resolved);
  }
  return *t;
}

bool is_named(const ir::Type& t) { return !t.name.empty(); }

std::string named_type_cpp(const ir::Type& t) { return cpp_ident(t.name); }

std::string integer_host_type(const ir::IntegerDesc& d) {
  if (d.host_bits) {
    if (!d.is_signed) {
      switch (*d.host_bits) {
        case 8:
          return "std::uint8_t";
        case 16:
          return "std::uint16_t";
        case 32:
          return "std::uint32_t";
        default:
          return "std::uint64_t";
      }
    }
    switch (*d.host_bits) {
      case 8:
        return "std::int8_t";
      case 16:
        return "std::int16_t";
      case 32:
        return "std::int32_t";
      default:
        return "std::int64_t";
    }
  }
  return "std::int64_t";
}

std::string opt_i64_expr(const std::optional<ir::BigInt>& b) {
  if (b && b->as_i64) {
    return "std::int64_t{" + std::to_string(*b->as_i64) + "}";
  }
  return "std::nullopt";
}

std::string integer_constraint_expr(const ir::IntegerDesc& d) {
  std::ostringstream os;
  os << "asn1::per::IntegerConstraint{" << opt_i64_expr(d.constraint.lower) << ", "
     << opt_i64_expr(d.constraint.upper) << ", "
     << (d.constraint.extensible ? "true" : "false") << "}";
  return os.str();
}

std::string opt_size_expr(const std::optional<ir::BigInt>& b) {
  if (b && b->as_i64 && *b->as_i64 >= 0) {
    return "std::size_t{" + std::to_string(static_cast<std::uint64_t>(*b->as_i64)) + "}";
  }
  return "std::nullopt";
}

std::string size_constraint_expr(const ir::ConstraintDesc& d) {
  std::ostringstream os;
  os << "asn1::per::SizeConstraint{" << opt_size_expr(d.lower) << ", "
     << opt_size_expr(d.upper) << ", " << (d.extensible ? "true" : "false") << "}";
  return os.str();
}

class Emitter {
 public:
  Emitter(const ir::Model& model, EmitOptions options, Diagnostics& diag)
      : model_(model), options_(std::move(options)), diag_(diag) {}

  void run(std::ostream& header, std::ostream* source) {
    collect_named();
    emit_header(header);
    if (source) {
      *source << "// Generated by asn1cxx - companion TU (types are header-only).\n"
              << "#include \"" << options_.basename << ".hpp\"\n";
    }
  }

 private:
  const ir::Model& model_;
  EmitOptions options_;
  Diagnostics& diag_;
  std::vector<ir::TypeId> named_order_;
  std::unordered_set<ir::TypeId> named_set_;

  void collect_named() {
    auto consider = [&](ir::TypeId id) {
      const ir::Type& t = model_.arena.get(id);
      if (!is_named(t)) {
        return;
      }
      for (ir::TypeId existing : named_order_) {
        const ir::Type& e = model_.arena.get(existing);
        if (e.name == t.name && e.module == t.module) {
          return;
        }
      }
      named_set_.insert(id);
      named_order_.push_back(id);
    };
    for (ir::TypeId id : model_.exported_types) {
      consider(id);
    }
    for (std::size_t i = 0; i < model_.arena.type_count(); ++i) {
      consider(static_cast<ir::TypeId>(i));
    }
  }

  std::string type_cpp(ir::TypeId id, bool for_optional = false) {
    if (named_set_.count(id)) {
      return named_type_cpp(model_.arena.get(id));
    }
    const ir::Type& t = resolve(model_, id);
    if (is_named(t)) {
      for (ir::TypeId nid : named_order_) {
        const ir::Type& n = model_.arena.get(nid);
        if (n.name == t.name && n.module == t.module) {
          return named_type_cpp(n);
        }
      }
      return named_type_cpp(t);
    }
    return inline_type_cpp(t, for_optional);
  }

  std::string inline_type_cpp(const ir::Type& t, bool /*for_optional*/) {
    switch (t.kind) {
      case ir::TypeKind::Boolean:
        return "bool";
      case ir::TypeKind::Null:
        return "asn1_gen_detail::Null";
      case ir::TypeKind::Integer:
        return integer_host_type(t.integer);
      case ir::TypeKind::OctetString:
        return "std::vector<std::uint8_t>";
      case ir::TypeKind::BitString:
        return "asn1::per::BitStringValue";
      case ir::TypeKind::String:
        return "std::string";
      case ir::TypeKind::SequenceOf: {
        return "std::vector<" + type_cpp(t.sequence_of.element) + ">";
      }
      case ir::TypeKind::SetOf: {
        return "std::vector<" + type_cpp(t.set_of.element) + ">";
      }
      case ir::TypeKind::Enumerated:
        return "std::int64_t";
      case ir::TypeKind::ObjectIdentifier:
      case ir::TypeKind::RelativeOid:
        return "std::vector<std::uint64_t>";
      case ir::TypeKind::Sequence:
      case ir::TypeKind::Set:
      case ir::TypeKind::Choice:
        diag_.error({}, "anonymous SEQUENCE/SET/CHOICE nested types are not emitted as "
                         "inline structs; assign a type name");
        return "/*unsupported-anonymous*/void";
      case ir::TypeKind::Real:
        diag_.error({}, "REAL codegen is not implemented in Phase 12");
        return "double";
      case ir::TypeKind::Referenced:
        if (t.referenced.resolved != ir::kInvalidType) {
          return type_cpp(t.referenced.resolved);
        }
        diag_.error({}, "unresolved type reference '" + t.referenced.name + "'");
        return "void";
    }
    return "void";
  }

  void emit_header(std::ostream& out) {
    const std::string guard = "ASN1_GEN_" + cpp_ident(options_.basename) + "_HPP_";
    out << "// Generated by asn1cxx - do not edit.\n"
        << "#pragma once\n\n"
        << "#ifndef " << guard << "\n"
        << "#define " << guard << "\n\n"
        << "#include <asn1/runtime/bit_io.hpp>\n"
        << "#include <asn1/runtime/byte_io.hpp>\n"
        << "#include <asn1/runtime/per/codec.hpp>\n";
    if (options_.codec == CodecKind::Uper || options_.codec == CodecKind::Both) {
      out << "#include <asn1/runtime/uper.hpp>\n";
    }
    if (options_.codec == CodecKind::Aper || options_.codec == CodecKind::Both) {
      out << "#include <asn1/runtime/aper.hpp>\n";
    }
    out << "\n"
        << "#include <cstdint>\n"
        << "#include <optional>\n"
        << "#include <string>\n"
        << "#include <variant>\n"
        << "#include <vector>\n\n"
        << "namespace asn1_gen_detail {\n"
        << "struct Null {};\n"
        << "}  // namespace asn1_gen_detail\n\n"
        << "namespace " << cpp_ident(options_.namespace_name) << " {\n\n";

    // Forward declarations for named sequence/choice.
    for (ir::TypeId id : named_order_) {
      const ir::Type& t = model_.arena.get(id);
      if (t.kind == ir::TypeKind::Sequence || t.kind == ir::TypeKind::Set ||
          t.kind == ir::TypeKind::Choice) {
        out << "struct " << named_type_cpp(t) << ";\n";
      }
    }
    out << "\n";

    for (ir::TypeId id : named_order_) {
      emit_type_decl(out, id);
      out << "\n";
    }

    for (ir::TypeId id : named_order_) {
      if (options_.codec == CodecKind::Uper || options_.codec == CodecKind::Both) {
        emit_codec_fns(out, id, /*aper=*/false);
      }
      if (options_.codec == CodecKind::Aper || options_.codec == CodecKind::Both) {
        emit_codec_fns(out, id, /*aper=*/true);
      }
    }

    out << "}  // namespace " << cpp_ident(options_.namespace_name) << "\n\n"
        << "#endif  // " << guard << "\n";
  }

  void emit_type_decl(std::ostream& out, ir::TypeId id) {
    const ir::Type& t = model_.arena.get(id);
    const std::string name = named_type_cpp(t);
    switch (t.kind) {
      case ir::TypeKind::Boolean:
        out << "using " << name << " = bool;\n";
        break;
      case ir::TypeKind::Null:
        out << "using " << name << " = asn1_gen_detail::Null;\n";
        break;
      case ir::TypeKind::Integer:
        out << "using " << name << " = " << integer_host_type(t.integer) << ";\n";
        break;
      case ir::TypeKind::OctetString:
        out << "using " << name << " = std::vector<std::uint8_t>;\n";
        break;
      case ir::TypeKind::BitString:
        out << "using " << name << " = asn1::per::BitStringValue;\n";
        break;
      case ir::TypeKind::String:
        out << "using " << name << " = std::string;\n";
        break;
      case ir::TypeKind::SequenceOf:
        out << "struct " << name << " {\n"
            << "  std::vector<" << type_cpp(t.sequence_of.element) << "> value;\n"
            << "};\n";
        break;
      case ir::TypeKind::SetOf:
        out << "struct " << name << " {\n"
            << "  std::vector<" << type_cpp(t.set_of.element) << "> value;\n"
            << "};\n";
        break;
      case ir::TypeKind::Enumerated: {
        out << "enum class " << name << " : std::int64_t {\n";
        for (const auto& nn : t.enumerated.root) {
          out << "  " << cpp_ident(nn.name);
          if (nn.value.as_i64) {
            out << " = " << *nn.value.as_i64;
          }
          out << ",\n";
        }
        for (const auto& nn : t.enumerated.extensions) {
          out << "  " << cpp_ident(nn.name);
          if (nn.value.as_i64) {
            out << " = " << *nn.value.as_i64;
          }
          out << ",\n";
        }
        out << "};\n";
        break;
      }
      case ir::TypeKind::ObjectIdentifier:
      case ir::TypeKind::RelativeOid:
        out << "using " << name << " = std::vector<std::uint64_t>;\n";
        break;
      case ir::TypeKind::Real:
        out << "using " << name << " = double;  // REAL encode/decode not generated\n";
        break;
      case ir::TypeKind::Set: {
        out << "struct " << name << " {\n";
        for (const ir::Field& f : t.set.root) {
          const std::string field_ty = type_cpp(f.type);
          const std::string field_name = cpp_ident(f.name);
          if (f.presence == ir::Presence::Optional || f.presence == ir::Presence::Default) {
            out << "  std::optional<" << field_ty << "> " << field_name << ";\n";
          } else {
            out << "  " << field_ty << " " << field_name << ";\n";
          }
        }
        out << "};\n";
        break;
      }
      case ir::TypeKind::Sequence: {
        out << "struct " << name << " {\n";
        for (const ir::Field& f : t.sequence.root) {
          const std::string field_ty = type_cpp(f.type);
          const std::string field_name = cpp_ident(f.name);
          if (f.presence == ir::Presence::Optional || f.presence == ir::Presence::Default) {
            out << "  std::optional<" << field_ty << "> " << field_name << ";\n";
          } else {
            out << "  " << field_ty << " " << field_name << ";\n";
          }
        }
        out << "};\n";
        break;
      }
      case ir::TypeKind::Choice: {
        out << "struct " << name << " {\n";
        for (const ir::Field& f : t.choice.alternatives) {
          out << "  struct " << cpp_ident(f.name) << "_ {\n"
              << "    " << type_cpp(f.type) << " value;\n"
              << "  };\n";
        }
        out << "  std::variant<";
        for (std::size_t i = 0; i < t.choice.alternatives.size(); ++i) {
          if (i) {
            out << ", ";
          }
          out << cpp_ident(t.choice.alternatives[i].name) << "_";
        }
        out << "> alt;\n};\n";
        break;
      }
      case ir::TypeKind::Referenced:
        out << "// skipped unresolved/alias " << name << "\n";
        break;
    }
  }

  const char* ns_codec(bool aper) const { return aper ? "asn1::aper" : "asn1::uper"; }
  const char* fn_suffix(bool aper) const { return aper ? "aper" : "uper"; }

  void emit_codec_fns(std::ostream& out, ir::TypeId id, bool aper) {
    const ir::Type& t = model_.arena.get(id);
    const std::string name = named_type_cpp(t);
    const std::string enc = std::string("encode_") + fn_suffix(aper);
    const std::string dec = std::string("decode_") + fn_suffix(aper);

    out << "inline asn1::Result<void> " << enc << "(asn1::BitWriter& w, const " << name
        << "& value) {\n";
    emit_encode_body(out, t, "value", aper, "  ");
    out << "  return asn1::Result<void>::success();\n}\n\n";

    out << "inline asn1::Result<" << name << "> " << dec << "(asn1::BitReader& r) {\n";
    out << "  " << name << " value{};\n";
    emit_decode_body(out, t, "value", aper, "  ");
    out << "  return value;\n}\n\n";
  }


  static std::vector<std::int64_t> enum_root_sorted_values(const ir::EnumeratedDesc& e) {
    std::vector<std::int64_t> vals;
    vals.reserve(e.root.size());
    for (const auto& nn : e.root) {
      vals.push_back(nn.value.as_i64 ? *nn.value.as_i64 : 0);
    }
    std::sort(vals.begin(), vals.end());
    return vals;
  }

  void emit_encode_body(std::ostream& out, const ir::Type& t, const std::string& expr,
                        bool aper, const std::string& ind) {
    const char* C = ns_codec(aper);
    switch (t.kind) {
      case ir::TypeKind::Boolean:
        out << ind << C << "::encode_boolean(w, " << expr << ");\n";
        break;
      case ir::TypeKind::Null:
        out << ind << C << "::encode_null(w);\n";
        break;
      case ir::TypeKind::Integer:
        out << ind << C << "::encode_integer(w, static_cast<std::int64_t>(" << expr << "), "
            << integer_constraint_expr(t.integer) << ");\n";
        break;
      case ir::TypeKind::OctetString:
        out << ind << C << "::encode_octet_string(w, " << expr << ", "
            << size_constraint_expr(t.octet_string.size) << ");\n";
        break;
      case ir::TypeKind::BitString:
        out << ind << C << "::encode_bit_string(w, " << expr << ".bits, " << expr
            << ".bit_length, " << size_constraint_expr(t.bit_string.size) << ");\n";
        break;
      case ir::TypeKind::String:
        out << ind << C << "::encode_utf8_string(w, " << expr << ", "
            << size_constraint_expr(t.string.size) << ");\n";
        break;
      case ir::TypeKind::SequenceOf: {
        const ir::Type& elem = resolve(model_, t.sequence_of.element);
        out << ind << C << "::encode_sequence_of_length(w, " << expr << ".value.size(), "
            << size_constraint_expr(t.sequence_of.size) << ");\n";
        out << ind << "for (const auto& elem : " << expr << ".value) {\n";
        if (is_named(elem)) {
          out << ind << "  if (auto r = encode_" << fn_suffix(aper) << "(w, elem); !r) return r;\n";
        } else {
          emit_encode_body(out, elem, "elem", aper, ind + "  ");
        }
        out << ind << "}\n";
        break;
      }

      case ir::TypeKind::SetOf: {
        const ir::Type& elem = resolve(model_, t.set_of.element);
        out << ind << C << "::encode_sequence_of_length(w, " << expr << ".value.size(), "
            << size_constraint_expr(t.set_of.size) << ");\n";
        out << ind << "for (const auto& elem : " << expr << ".value) {\n";
        if (is_named(elem)) {
          out << ind << "  if (auto r = encode_" << fn_suffix(aper) << "(w, elem); !r) return r;\n";
        } else {
          emit_encode_body(out, elem, "elem", aper, ind + "  ");
        }
        out << ind << "}\n";
        break;
      }
      case ir::TypeKind::Enumerated: {
        const auto vals = enum_root_sorted_values(t.enumerated);
        out << ind << "{\n";
        out << ind << "  std::size_t idx = 0;\n";
        out << ind << "  switch (static_cast<std::int64_t>(" << expr << ")) {\n";
        for (std::size_t i = 0; i < vals.size(); ++i) {
          out << ind << "    case " << vals[i] << ": idx = " << i << "; break;\n";
        }
        out << ind << "    default: idx = 0; break;\n";
        out << ind << "  }\n";
        out << ind << "  " << C << "::encode_enumerated(w, idx, "
            << t.enumerated.root.size() << ", "
            << (t.enumerated.extensible ? "true" : "false") << ");\n";
        out << ind << "}\n";
        break;
      }
      case ir::TypeKind::ObjectIdentifier:
        out << ind << C << "::encode_object_identifier(w, " << expr << ", false);\n";
        break;
      case ir::TypeKind::RelativeOid:
        out << ind << C << "::encode_object_identifier(w, " << expr << ", true);\n";
        break;
      case ir::TypeKind::Real:
        out << ind
            << "return asn1::make_error(asn1::Error::Code::Unsupported, 0, "
               "\"REAL encoding not implemented\");\n";
        break;
      case ir::TypeKind::Set: {
        std::vector<const ir::Field*> optionals;
        for (const ir::Field& f : t.set.root) {
          if (f.presence == ir::Presence::Optional || f.presence == ir::Presence::Default) {
            optionals.push_back(&f);
          }
        }
        out << ind << "{\n";
        out << ind << "  std::uint8_t opt[" << (optionals.empty() ? 1 : optionals.size())
            << "] = {};\n";
        for (std::size_t i = 0; i < optionals.size(); ++i) {
          out << ind << "  opt[" << i << "] = " << expr << "." << cpp_ident(optionals[i]->name)
              << ".has_value() ? 1 : 0;\n";
        }
        out << ind << "  " << C << "::encode_sequence_preamble(w, "
            << (t.set.extensible ? "true" : "false")
            << ", asn1::Span<const std::uint8_t>(opt, " << optionals.size() << "));\n";
        out << ind << "}\n";
        for (const ir::Field& f : t.set.root) {
          const std::string fname = cpp_ident(f.name);
          const ir::Type& ft = resolve(model_, f.type);
          const bool optional =
              f.presence == ir::Presence::Optional || f.presence == ir::Presence::Default;
          if (optional) {
            out << ind << "if (" << expr << "." << fname << ") {\n";
            emit_field_encode(out, ft, expr + "." + fname + ".value()", aper, ind + "  ");
            out << ind << "}\n";
          } else {
            emit_field_encode(out, ft, expr + "." + fname, aper, ind);
          }
        }
        break;
      }
      case ir::TypeKind::Sequence: {
        std::vector<const ir::Field*> optionals;
        for (const ir::Field& f : t.sequence.root) {
          if (f.presence == ir::Presence::Optional || f.presence == ir::Presence::Default) {
            optionals.push_back(&f);
          }
        }
        out << ind << "{\n";
        out << ind << "  std::uint8_t opt[" << (optionals.empty() ? 1 : optionals.size())
            << "] = {};\n";
        for (std::size_t i = 0; i < optionals.size(); ++i) {
          out << ind << "  opt[" << i << "] = " << expr << "." << cpp_ident(optionals[i]->name)
              << ".has_value() ? 1 : 0;\n";
        }
        out << ind << "  " << C << "::encode_sequence_preamble(w, "
            << (t.sequence.extensible ? "true" : "false")
            << ", asn1::Span<const std::uint8_t>(opt, " << optionals.size() << "));\n";
        out << ind << "}\n";
        for (const ir::Field& f : t.sequence.root) {
          const std::string fname = cpp_ident(f.name);
          const ir::Type& ft = resolve(model_, f.type);
          const bool optional =
              f.presence == ir::Presence::Optional || f.presence == ir::Presence::Default;
          if (optional) {
            out << ind << "if (" << expr << "." << fname << ") {\n";
            emit_field_encode(out, ft, expr + "." + fname + ".value()", aper, ind + "  ");
            out << ind << "}\n";
          } else {
            emit_field_encode(out, ft, expr + "." + fname, aper, ind);
          }
        }
        break;
      }
      case ir::TypeKind::Choice: {
        out << ind << "{\n";
        out << ind << "  const std::size_t index = " << expr << ".alt.index();\n";
        out << ind << "  " << C << "::encode_choice_root(w, index, "
            << t.choice.alternatives.size() << ", "
            << (t.choice.extensible ? "true" : "false") << ");\n";
        out << ind << "  switch (index) {\n";
        for (std::size_t i = 0; i < t.choice.alternatives.size(); ++i) {
          const ir::Field& f = t.choice.alternatives[i];
          const ir::Type& ft = resolve(model_, f.type);
          out << ind << "    case " << i << ":\n";
          out << ind << "      {\n";
          out << ind << "        const auto& alt = std::get<" << i << ">(" << expr
              << ".alt);\n";
          emit_field_encode(out, ft, "alt.value", aper, ind + "        ");
          out << ind << "        break;\n";
          out << ind << "      }\n";
        }
        out << ind << "    default:\n";
        out << ind
            << "      return asn1::make_error(asn1::Error::Code::InvalidArgument, w.bit_size(), "
               "\"CHOICE index out of range\");\n";
        out << ind << "  }\n";
        out << ind << "}\n";
        break;
      }
      case ir::TypeKind::Referenced:
        if (t.referenced.resolved != ir::kInvalidType) {
          emit_encode_body(out, resolve(model_, t.referenced.resolved), expr, aper, ind);
        }
        break;
    }
  }

  void emit_field_encode(std::ostream& out, const ir::Type& ft, const std::string& expr,
                         bool aper, const std::string& ind) {
    if (is_named(ft)) {
      out << ind << "if (auto r = encode_" << fn_suffix(aper) << "(w, " << expr
          << "); !r) return r;\n";
    } else {
      emit_encode_body(out, ft, expr, aper, ind);
    }
  }

  void emit_decode_body(std::ostream& out, const ir::Type& t, const std::string& expr,
                        bool aper, const std::string& ind) {
    const char* C = ns_codec(aper);
    switch (t.kind) {
      case ir::TypeKind::Boolean:
        out << ind << "{\n"
            << ind << "  auto tmp = " << C << "::decode_boolean(r);\n"
            << ind << "  if (!tmp) return tmp.error();\n"
            << ind << "  " << expr << " = tmp.value();\n"
            << ind << "}\n";
        break;
      case ir::TypeKind::Null:
        out << ind << "{\n"
            << ind << "  auto tmp = " << C << "::decode_null(r);\n"
            << ind << "  if (!tmp) return tmp.error();\n"
            << ind << "}\n";
        break;
      case ir::TypeKind::Integer:
        out << ind << "{\n"
            << ind << "  auto tmp = " << C << "::decode_integer(r, "
            << integer_constraint_expr(t.integer) << ");\n"
            << ind << "  if (!tmp) return tmp.error();\n"
            << ind << "  " << expr << " = static_cast<" << integer_host_type(t.integer)
            << ">(tmp.value());\n"
            << ind << "}\n";
        break;
      case ir::TypeKind::OctetString:
        out << ind << "{\n"
            << ind << "  auto tmp = " << C << "::decode_octet_string(r, "
            << size_constraint_expr(t.octet_string.size) << ");\n"
            << ind << "  if (!tmp) return tmp.error();\n"
            << ind << "  " << expr << " = std::move(tmp.value());\n"
            << ind << "}\n";
        break;
      case ir::TypeKind::BitString:
        out << ind << "{\n"
            << ind << "  auto tmp = " << C << "::decode_bit_string(r, "
            << size_constraint_expr(t.bit_string.size) << ");\n"
            << ind << "  if (!tmp) return tmp.error();\n"
            << ind << "  " << expr << " = std::move(tmp.value());\n"
            << ind << "}\n";
        break;
      case ir::TypeKind::String:
        out << ind << "{\n"
            << ind << "  auto tmp = " << C << "::decode_utf8_string(r, "
            << size_constraint_expr(t.string.size) << ");\n"
            << ind << "  if (!tmp) return tmp.error();\n"
            << ind << "  " << expr << " = std::move(tmp.value());\n"
            << ind << "}\n";
        break;
      case ir::TypeKind::SequenceOf: {
        const ir::Type& elem_t = resolve(model_, t.sequence_of.element);
        out << ind << "{\n"
            << ind << "  auto n = " << C << "::decode_sequence_of_length(r, "
            << size_constraint_expr(t.sequence_of.size) << ");\n"
            << ind << "  if (!n) return n.error();\n"
            << ind << "  " << expr << ".value.clear();\n"
            << ind << "  " << expr << ".value.reserve(n.value());\n"
            << ind << "  for (std::size_t i = 0; i < n.value(); ++i) {\n"
            << ind << "    " << type_cpp(t.sequence_of.element) << " elem{};\n";
        if (is_named(elem_t)) {
          out << ind << "    auto tmp = decode_" << fn_suffix(aper) << "(r);\n"
              << ind << "    if (!tmp) return tmp.error();\n"
              << ind << "    elem = std::move(tmp.value());\n";
        } else {
          emit_decode_body(out, elem_t, "elem", aper, ind + "    ");
        }
        out << ind << "    " << expr << ".value.push_back(std::move(elem));\n"
            << ind << "  }\n"
            << ind << "}\n";
        break;
      }

      case ir::TypeKind::SetOf: {
        const ir::Type& elem_t = resolve(model_, t.set_of.element);
        out << ind << "{\n"
            << ind << "  auto n = " << C << "::decode_sequence_of_length(r, "
            << size_constraint_expr(t.set_of.size) << ");\n"
            << ind << "  if (!n) return n.error();\n"
            << ind << "  " << expr << ".value.clear();\n"
            << ind << "  " << expr << ".value.reserve(n.value());\n"
            << ind << "  for (std::size_t i = 0; i < n.value(); ++i) {\n"
            << ind << "    " << type_cpp(t.set_of.element) << " elem{};\n";
        if (is_named(elem_t)) {
          out << ind << "    auto tmp = decode_" << fn_suffix(aper) << "(r);\n"
              << ind << "    if (!tmp) return tmp.error();\n"
              << ind << "    elem = std::move(tmp.value());\n";
        } else {
          emit_decode_body(out, elem_t, "elem", aper, ind + "    ");
        }
        out << ind << "    " << expr << ".value.push_back(std::move(elem));\n"
            << ind << "  }\n"
            << ind << "}\n";
        break;
      }
      case ir::TypeKind::Enumerated: {
        const auto vals = enum_root_sorted_values(t.enumerated);
        out << ind << "{\n"
            << ind << "  auto idx = " << C << "::decode_enumerated(r, "
            << t.enumerated.root.size() << ", "
            << (t.enumerated.extensible ? "true" : "false") << ");\n"
            << ind << "  if (!idx) return idx.error();\n"
            << ind << "  switch (idx.value()) {\n";
        for (std::size_t i = 0; i < vals.size(); ++i) {
          out << ind << "    case " << i << ": " << expr << " = static_cast<"
              << (is_named(t) ? named_type_cpp(t) : "std::int64_t") << ">(" << vals[i]
              << "); break;\n";
        }
        out << ind << "    default: " << expr << " = static_cast<"
            << (is_named(t) ? named_type_cpp(t) : "std::int64_t") << ">(0); break;\n";
        out << ind << "  }\n"
            << ind << "}\n";
        break;
      }
      case ir::TypeKind::ObjectIdentifier:
        out << ind << "{\n"
            << ind << "  auto tmp = " << C << "::decode_object_identifier(r, false);\n"
            << ind << "  if (!tmp) return tmp.error();\n"
            << ind << "  " << expr << " = std::move(tmp.value());\n"
            << ind << "}\n";
        break;
      case ir::TypeKind::RelativeOid:
        out << ind << "{\n"
            << ind << "  auto tmp = " << C << "::decode_object_identifier(r, true);\n"
            << ind << "  if (!tmp) return tmp.error();\n"
            << ind << "  " << expr << " = std::move(tmp.value());\n"
            << ind << "}\n";
        break;
      case ir::TypeKind::Real:
        out << ind
            << "return asn1::make_error(asn1::Error::Code::Unsupported, r.bit_offset(), "
               "\"REAL decoding not implemented\");\n";
        break;
      case ir::TypeKind::Set: {
        std::vector<const ir::Field*> optionals;
        for (const ir::Field& f : t.set.root) {
          if (f.presence == ir::Presence::Optional || f.presence == ir::Presence::Default) {
            optionals.push_back(&f);
          }
        }
        out << ind << "{\n"
            << ind << "  auto bm = " << C << "::decode_sequence_preamble(r, "
            << (t.set.extensible ? "true" : "false") << ", " << optionals.size()
            << ");\n"
            << ind << "  if (!bm) return bm.error();\n";
        std::size_t opt_i = 0;
        for (const ir::Field& f : t.set.root) {
          const std::string fname = cpp_ident(f.name);
          const ir::Type& ft = resolve(model_, f.type);
          const bool optional =
              f.presence == ir::Presence::Optional || f.presence == ir::Presence::Default;
          if (optional) {
            out << ind << "  if (bm.value().size() > " << opt_i << " && bm.value()[" << opt_i
                << "]) {\n"
                << ind << "    " << type_cpp(f.type) << " field{};\n";
            emit_field_decode(out, ft, "field", aper, ind + "    ");
            out << ind << "    " << expr << "." << fname << " = std::move(field);\n"
                << ind << "  } else {\n"
                << ind << "    " << expr << "." << fname << " = std::nullopt;\n"
                << ind << "  }\n";
            ++opt_i;
          } else {
            emit_field_decode(out, ft, expr + "." + fname, aper, ind + "  ");
          }
        }
        out << ind << "}\n";
        break;
      }
      case ir::TypeKind::Sequence: {
        std::vector<const ir::Field*> optionals;
        for (const ir::Field& f : t.sequence.root) {
          if (f.presence == ir::Presence::Optional || f.presence == ir::Presence::Default) {
            optionals.push_back(&f);
          }
        }
        out << ind << "{\n"
            << ind << "  auto bm = " << C << "::decode_sequence_preamble(r, "
            << (t.sequence.extensible ? "true" : "false") << ", " << optionals.size()
            << ");\n"
            << ind << "  if (!bm) return bm.error();\n";
        std::size_t opt_i = 0;
        for (const ir::Field& f : t.sequence.root) {
          const std::string fname = cpp_ident(f.name);
          const ir::Type& ft = resolve(model_, f.type);
          const bool optional =
              f.presence == ir::Presence::Optional || f.presence == ir::Presence::Default;
          if (optional) {
            out << ind << "  if (bm.value().size() > " << opt_i << " && bm.value()[" << opt_i
                << "]) {\n"
                << ind << "    " << type_cpp(f.type) << " field{};\n";
            emit_field_decode(out, ft, "field", aper, ind + "    ");
            out << ind << "    " << expr << "." << fname << " = std::move(field);\n"
                << ind << "  } else {\n"
                << ind << "    " << expr << "." << fname << " = std::nullopt;\n"
                << ind << "  }\n";
            ++opt_i;
          } else {
            emit_field_decode(out, ft, expr + "." + fname, aper, ind + "  ");
          }
        }
        out << ind << "}\n";
        break;
      }
      case ir::TypeKind::Choice: {
        out << ind << "{\n"
            << ind << "  auto idx = " << C << "::decode_choice_root(r, "
            << t.choice.alternatives.size() << ", "
            << (t.choice.extensible ? "true" : "false") << ");\n"
            << ind << "  if (!idx) return idx.error();\n"
            << ind << "  switch (idx.value()) {\n";
        for (std::size_t i = 0; i < t.choice.alternatives.size(); ++i) {
          const ir::Field& f = t.choice.alternatives[i];
          const ir::Type& ft = resolve(model_, f.type);
          out << ind << "    case " << i << ": {\n"
              << ind << "      " << named_type_cpp(t) << "::" << cpp_ident(f.name)
              << "_ alt{};\n";
          emit_field_decode(out, ft, "alt.value", aper, ind + "      ");
          out << ind << "      " << expr << ".alt = std::move(alt);\n"
              << ind << "      break;\n"
              << ind << "    }\n";
        }
        out << ind << "    default:\n"
            << ind
            << "      return asn1::make_error(asn1::Error::Code::InvalidArgument, r.bit_offset(), "
               "\"CHOICE index out of range\");\n"
            << ind << "  }\n"
            << ind << "}\n";
        break;
      }
      case ir::TypeKind::Referenced:
        if (t.referenced.resolved != ir::kInvalidType) {
          emit_decode_body(out, resolve(model_, t.referenced.resolved), expr, aper, ind);
        }
        break;
    }
  }

  void emit_field_decode(std::ostream& out, const ir::Type& ft, const std::string& expr,
                         bool aper, const std::string& ind) {
    if (is_named(ft)) {
      out << ind << "{\n"
          << ind << "  auto tmp = decode_" << fn_suffix(aper) << "(r);\n"
          << ind << "  if (!tmp) return tmp.error();\n"
          << ind << "  " << expr << " = std::move(tmp.value());\n"
          << ind << "}\n";
    } else {
      emit_decode_body(out, ft, expr, aper, ind);
    }
  }
};

}  // namespace

void CppGenerator::emit(const ir::Model& model, const EmitOptions& options, Diagnostics& diag,
                        std::ostream& header, std::ostream* source) {
  Emitter emitter(model, options, diag);
  emitter.run(header, source);
}

std::string CppGenerator::emit_header_string(const ir::Model& model, const EmitOptions& options,
                                             Diagnostics& diag) {
  std::ostringstream os;
  emit(model, options, diag, os, nullptr);
  return os.str();
}

}  // namespace codegen
}  // namespace asn1
