#include <asn1/frontend/token.hpp>

namespace asn1 {

const char* to_string(TokenKind kind) {
  switch (kind) {
    case TokenKind::EndOfFile:
      return "end-of-file";
    case TokenKind::TypeReference:
      return "type-reference";
    case TokenKind::Identifier:
      return "identifier";
    case TokenKind::Number:
      return "number";
    case TokenKind::RealNumber:
      return "real-number";
    case TokenKind::BinaryString:
      return "binary-string";
    case TokenKind::HexString:
      return "hex-string";
    case TokenKind::CharacterString:
      return "character-string";
    case TokenKind::Assign:
      return "::=";
    case TokenKind::Range:
      return "..";
    case TokenKind::Ellipsis:
      return "...";
    case TokenKind::VersionLBracket:
      return "[[";
    case TokenKind::VersionRBracket:
      return "]]";
    case TokenKind::LBrace:
      return "{";
    case TokenKind::RBrace:
      return "}";
    case TokenKind::LBracket:
      return "[";
    case TokenKind::RBracket:
      return "]";
    case TokenKind::LParen:
      return "(";
    case TokenKind::RParen:
      return ")";
    case TokenKind::Comma:
      return ",";
    case TokenKind::Semicolon:
      return ";";
    case TokenKind::VerticalBar:
      return "|";
    case TokenKind::Caret:
      return "^";
    case TokenKind::Colon:
      return ":";
    case TokenKind::At:
      return "@";
    case TokenKind::Exclamation:
      return "!";
    case TokenKind::Less:
      return "<";
    case TokenKind::Greater:
      return ">";
    case TokenKind::Minus:
      return "-";
    case TokenKind::KwABSENT:
      return "ABSENT";
    case TokenKind::KwABSTRACT_SYNTAX:
      return "ABSTRACT-SYNTAX";
    case TokenKind::KwALL:
      return "ALL";
    case TokenKind::KwAPPLICATION:
      return "APPLICATION";
    case TokenKind::KwAUTOMATIC:
      return "AUTOMATIC";
    case TokenKind::KwBEGIN:
      return "BEGIN";
    case TokenKind::KwBIT:
      return "BIT";
    case TokenKind::KwBMPString:
      return "BMPString";
    case TokenKind::KwBOOLEAN:
      return "BOOLEAN";
    case TokenKind::KwBY:
      return "BY";
    case TokenKind::KwCHARACTER:
      return "CHARACTER";
    case TokenKind::KwCHOICE:
      return "CHOICE";
    case TokenKind::KwCLASS:
      return "CLASS";
    case TokenKind::KwCOMPONENT:
      return "COMPONENT";
    case TokenKind::KwCOMPONENTS:
      return "COMPONENTS";
    case TokenKind::KwCONSTRAINED:
      return "CONSTRAINED";
    case TokenKind::KwCONTAINING:
      return "CONTAINING";
    case TokenKind::KwDEFAULT:
      return "DEFAULT";
    case TokenKind::KwDEFINITIONS:
      return "DEFINITIONS";
    case TokenKind::KwEMBEDDED:
      return "EMBEDDED";
    case TokenKind::KwEND:
      return "END";
    case TokenKind::KwENUMERATED:
      return "ENUMERATED";
    case TokenKind::KwEXCEPT:
      return "EXCEPT";
    case TokenKind::KwEXPLICIT:
      return "EXPLICIT";
    case TokenKind::KwEXPORTS:
      return "EXPORTS";
    case TokenKind::KwEXTENSIBILITY:
      return "EXTENSIBILITY";
    case TokenKind::KwEXTERNAL:
      return "EXTERNAL";
    case TokenKind::KwFALSE:
      return "FALSE";
    case TokenKind::KwFROM:
      return "FROM";
    case TokenKind::KwGeneralizedTime:
      return "GeneralizedTime";
    case TokenKind::KwGeneralString:
      return "GeneralString";
    case TokenKind::KwGraphicString:
      return "GraphicString";
    case TokenKind::KwIA5String:
      return "IA5String";
    case TokenKind::KwIDENTIFIER:
      return "IDENTIFIER";
    case TokenKind::KwIMPLICIT:
      return "IMPLICIT";
    case TokenKind::KwIMPLIED:
      return "IMPLIED";
    case TokenKind::KwIMPORTS:
      return "IMPORTS";
    case TokenKind::KwINCLUDES:
      return "INCLUDES";
    case TokenKind::KwINSTANCE:
      return "INSTANCE";
    case TokenKind::KwINTEGER:
      return "INTEGER";
    case TokenKind::KwINTERSECTION:
      return "INTERSECTION";
    case TokenKind::KwISO646String:
      return "ISO646String";
    case TokenKind::KwMAX:
      return "MAX";
    case TokenKind::KwMIN:
      return "MIN";
    case TokenKind::KwMINUS_INFINITY:
      return "MINUS-INFINITY";
    case TokenKind::KwNULL:
      return "NULL";
    case TokenKind::KwNumericString:
      return "NumericString";
    case TokenKind::KwOBJECT:
      return "OBJECT";
    case TokenKind::KwObjectDescriptor:
      return "ObjectDescriptor";
    case TokenKind::KwOCTET:
      return "OCTET";
    case TokenKind::KwOF:
      return "OF";
    case TokenKind::KwOPTIONAL:
      return "OPTIONAL";
    case TokenKind::KwPATTERN:
      return "PATTERN";
    case TokenKind::KwPDV:
      return "PDV";
    case TokenKind::KwPLUS_INFINITY:
      return "PLUS-INFINITY";
    case TokenKind::KwPRESENT:
      return "PRESENT";
    case TokenKind::KwPrintableString:
      return "PrintableString";
    case TokenKind::KwPRIVATE:
      return "PRIVATE";
    case TokenKind::KwREAL:
      return "REAL";
    case TokenKind::KwRELATIVE_OID:
      return "RELATIVE-OID";
    case TokenKind::KwSEQUENCE:
      return "SEQUENCE";
    case TokenKind::KwSET:
      return "SET";
    case TokenKind::KwSIZE:
      return "SIZE";
    case TokenKind::KwSTRING:
      return "STRING";
    case TokenKind::KwSYNTAX:
      return "SYNTAX";
    case TokenKind::KwT61String:
      return "T61String";
    case TokenKind::KwTAGS:
      return "TAGS";
    case TokenKind::KwTeletexString:
      return "TeletexString";
    case TokenKind::KwTRUE:
      return "TRUE";
    case TokenKind::KwTYPE_IDENTIFIER:
      return "TYPE-IDENTIFIER";
    case TokenKind::KwUNION:
      return "UNION";
    case TokenKind::KwUNIQUE:
      return "UNIQUE";
    case TokenKind::KwUNIVERSAL:
      return "UNIVERSAL";
    case TokenKind::KwUniversalString:
      return "UniversalString";
    case TokenKind::KwUTCTime:
      return "UTCTime";
    case TokenKind::KwUTF8String:
      return "UTF8String";
    case TokenKind::KwVideotexString:
      return "VideotexString";
    case TokenKind::KwVisibleString:
      return "VisibleString";
    case TokenKind::KwWITH:
      return "WITH";
    case TokenKind::Invalid:
      return "invalid";
  }
  return "unknown";
}

}  // namespace asn1
